apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vw27uk6g7-go
  janus-idp.io/tekton: vw27uk6g7-go
  backstage.io/kubernetes-id: vw27uk6g7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vw27uk6g7-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
